jobs:
  - name: development
    max_in_flight: 1
    plan:
      - in_parallel:
        - get: meta
          resource: meta-development
        - get: dataworks-aws-data-ingress
          trigger: true
        - get: dataworks-behavioural-framework
          trigger: false
        - .: (( inject meta.plan.get-dw-al2-ecs-ami ))
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'default'
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'default'
      - .: (( inject meta.plan.e2e-test))
        params:
          TF_WORKSPACE: development
          AWS_ACC: ((aws_account.development))
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
    .: (( inject meta.plan.notify ))

  - name: cycle-data-ingress-development
    plan:
      - .: (( inject meta.plan.cycle-containers ))
        params:
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
          CLUSTER: data-ingress
          SERVICE: sft_agent_receiver
    .: (( inject meta.plan.notify ))
