jobs:
- name: production
  max_in_flight: 1
  plan:
    - in_parallel:
      - get: dataworks-aws-data-ingress
        trigger: true
        passed:
          - preprod
      - .: (( inject meta.plan.get-dw-al2-ecs-ami ))
        passed:
          - preprod
    - .: (( inject meta.plan.terraform-bootstrap ))
    - .: (( inject meta.plan.terraform-apply ))
      params:
        TF_WORKSPACE: production
    - .: (( inject meta.plan.terraform-plan ))
      params:
        TF_WORKSPACE: production

- name: cycle-data-ingress-production
  plan:
    - .: (( inject meta.plan.cycle-containers ))
      params:
        AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
        CLUSTER: data-ingress
        SERVICE: data-ingress
